name: GenPvP
version: '2.0'
main: com.pallux.genpvp.GenPvP
api-version: '1.19'
author: Pallux
description: Generator PvP Plugin with upgradable generators, levels, and cubes
website: https://pallux.com
softdepend: [Vault, PlaceholderAPI, WorldGuard]

commands:
  gpvp:
    description: Main GenPvP command
    usage: /gpvp <gen|defense|cube|armor|level|shop|armory|gems|stats|reload>
    aliases: []

  level:
    description: Opens level up GUI
    usage: /level
    aliases: [levelup]

  gens:
    description: Opens generator shop
    usage: /gens
    aliases: [generators]

  gems:
    description: Shows player gems
    usage: /gems
    aliases: []

  stats:
    description: Shows player statistics
    usage: /stats
    aliases: []

  armor:
    description: Opens armory GUI
    usage: /armor
    aliases: [armory]

  armory:
    description: Opens armory GUI
    usage: /armory
    aliases: []

  shop:
    description: Opens the main shop (generators and defense blocks)
    usage: /shop
    aliases: []

permissions:
  gpvp.admin:
    description: Access to all admin commands
    default: op
    children:
      gpvp.gen.give: true
      gpvp.gen.giveall: true
      gpvp.defense.give: true
      gpvp.defense.giveall: true
      gpvp.cube.give: true
      gpvp.cube.giveall: true
      gpvp.armor.give: true
      gpvp.gems.set: true
      gpvp.gems.add: true
      gpvp.gems.remove: true
      gpvp.reload: true

  gpvp.gen.give:
    description: Give generators to players
    default: op

  gpvp.gen.giveall:
    description: Give generators to all online players
    default: op

  gpvp.defense.give:
    description: Give defense blocks to players
    default: op

  gpvp.defense.giveall:
    description: Give defense blocks to all online players
    default: op

  gpvp.cube.give:
    description: Give cubes to players
    default: op

  gpvp.cube.giveall:
    description: Give cubes to all online players
    default: op

  gpvp.armor.give:
    description: Give armor to players
    default: op

  gpvp.gems.set:
    description: Set a player's gem balance.
    default: op

  gpvp.gems.add:
    description: Add gems to a player's balance.
    default: op

  gpvp.gems.remove:
    description: Remove gems from a player's balance.
    default: op

  gpvp.reload:
    description: Reload plugin configuration
    default: op

  gpvp.shop.tierunlock:
    description: Unlock all generator tiers in shop
    default: false

  gpvp.use:
    description: Basic plugin usage
    default: true